In [6]:
pip install integrate

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for integrate, since package 'wheel' is not installed.
  Running setup.py install for integrate: started
  Running setup.py install for integrate: finished with status 'done'
Note: you may need to restart the kernel to use updated packages.


In [ ]:
#using intergrate in scipy

In [6]:
from scipy import integrate

In [9]:
def  func(x,y):
    return x + y
integrate.dblquad(func, 0, 1, lambda x : 0, lambda x:2)

(3.0, 4.436070580899685e-14)

In [13]:
from scipy import optimize
import numpy as np

In [14]:
def f(x):
    return x**2 + 5*np.sin(x)
    

In [ ]:
#optimizing minmavalues in py

In [15]:
minmaValue = optimize.minimize(f, x0=2, method = 'bfgs', options = {'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [ ]:
#optimizing minmavalues in py without methods

In [17]:
minmaValue = optimize.minimize(f, x0 = 2, method = 'bfgs')
minmaValue

      fun: -3.2463942726915196
 hess_inv: array([[0.15445831]])
      jac: array([-4.47034836e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [ ]:
#inverse of matrix

In [19]:
matrix  = np.array([[10, 6], [2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [21]:
from scipy import linalg
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [ ]:
#finding the determinant

In [22]:
matrix = np.array([[4,9], [3,5]])
matrix

array([[4, 9],
       [3, 5]])

In [23]:
from scipy import linalg
linalg.det(matrix)

-6.999999999999999

In [24]:
#solve linear systems
numArray = np.array([[2,3,1], [-1,5,4], [3,2,9]])
numArray

array([[ 2,  3,  1],
       [-1,  5,  4],
       [ 3,  2,  9]])

In [26]:
numArrayValue = np.array([21,9,6])
numArrayValue

array([21,  9,  6])

In [28]:
from scipy import linalg
linalg.solve(numArray, numArrayValue)

array([ 4.95,  4.35, -1.95])

In [ ]:
#single value decomposition

In [29]:
numSvAddr = np.array([[3,5,1],[9,5,7]])

In [30]:
numSvAddr.shape

(2, 3)

In [31]:
linalg.svd(numSvAddr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [32]:
#eigenValues and Eigen Vectors

In [33]:
import numpy as np 
from scipy import linalg

In [35]:
test_data_matrix = np.array([[5,8], [7,9]])
eigenValues, eigenVectors = linalg.eig(test_data_matrix)
first_eigen, second_eigen = eigenValues

In [36]:
print(first_eigen, second_eigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [40]:
print(eigenVectors[:,0])

[-0.81220939  0.58336601]


In [41]:
print(eigenVectors[:,1])

[-0.63447346 -0.77294465]


In [ ]:
# perform Cdf(cummulatice distribution frequency) and Pdf(probability density function)

In [42]:
from scipy.stats import norm

In [43]:
norm.rvs(loc = 0, scale = 1, size = 20)

array([ 0.18972353, -0.51782946,  0.12143544,  0.2803996 ,  0.20331306,
       -2.00172366, -0.55186245, -0.07612275, -2.38377943,  1.05807367,
        0.78323627, -0.70739315,  0.05230174,  1.09873981, -0.29747321,
       -1.2523583 , -1.38041203,  1.12133479,  0.2222872 , -0.30653569])

In [44]:
norm.cdf(10, loc = 1, scale = 3)

0.9986501019683699

In [45]:
norm.pdf(10, loc = 1, scale =3)

0.001477282803979336

In [46]:
#grading movies 

In [47]:
def movie_grade(rating):
    if rating == 5:
        return 'A'
    if rating == 4:
        return 'B'
    if rating == 3:
        return 'C'
    else:
        return 'F'
        

In [48]:
#group by